### ISSUE TITLE
Crash voltage home and don't receive app notifications

### ISSUE THREAD

**Issue by root-Dante42** [cawilliamson/treble_voltage#15]
Hi 

The voltage home crash when I open YouTube, I imagine it is related to containing Google services

I don't receive notifications from any app even if they are set in the settings

Thank you for all wonderfull Woks!

My devices is motorola moto g62 5g

**Comment by cawilliamson** [comment]
Is your device running arm64 or arm32_binder64?

Do you have any logs of the crash so I can look in to the issue? :)

**Comment by root-Dante42** [comment]
my device is arm64
[crash.txt](https://github.com/cawilliamson/treble_voltage/files/14375984/crash.txt)

**Comment by cawilliamson** [comment]
Has this happened for all previous builds or just the latest?

I've never liked the VoltageOS launcher - I'm highly tempted to swap it out with something like Lawnchair to resolve these kinds of issues once and for all.

**Comment by root-Dante42** [comment]
i'm on the last build 
i tried to install lawnchair but i can't give permission to notification, for notification problems, do you suspect the problem is the launcher?

**Comment by cawilliamson** [comment]
Could you try the latest build and see if the problem is rectified?

**Comment by root-Dante42** [comment]
same problem on the last build (3.2-20240226)

**Comment by cawilliamson** [comment]
Sorry to keep asking millions of questions - was this a clean flash?

If not - you could try that. It's weird because nobody else has reported the issue you're seeing.

**Comment by root-Dante42** [comment]
I'm on clean flash 

I can log all crash and compare to see if anything changes between crashes

No problem for asking question

**Comment by cawilliamson** [comment]
I'm working on a build with Trebuchet as the default launcher. Will let you know once it's released so you can test to see if it fixes your issues. :)

**Comment by cawilliamson** [comment]
Give this build a try:

https://github.com/cawilliamson/treble_voltage/releases/tag/3.2-20240308

Uses Trebuchet launcher instead of the Voltage one - hopefully it should solve your problems. :)

**Comment by noguxx** [comment]
I was testing VoltageOS-arm64-ab-vndklite-3.2-20240226-UNOFFICIAL.img on a xiaomi Mi A2 and the only notification, that I notice, was not showing was **Android system** when connecting to PC the **USB debugging** and **USB preferences**.
I then tested the new VoltageOS-arm64-ab-vndklite-3.2-20240308-UNOFFICIAL.img but Trebuchet don't have an option to change row height of the App drawer, so I downgraded the system and somehow this fixed the **Android system** notification not showing, now the **USB debugging** and **USB preferences**  notifications are shown.

**Comment by cawilliamson** [comment]
> I was testing VoltageOS-arm64-ab-vndklite-3.2-20240226-UNOFFICIAL.img on a xiaomi Mi A2 and the only notification, that I notice, was not showing was **Android system** when connecting to PC the **USB debugging** and **USB preferences**. I then tested the new VoltageOS-arm64-ab-vndklite-3.2-20240308-UNOFFICIAL.img but Trebuchet don't have an option to change row height of the App drawer, so I downgraded the system and somehow this fixed the **Android system** notification not showing, now the **USB debugging** and **USB preferences** notifications are shown.

Cool, glad to hear you sorted it.

Regarding Trebuchet vs Voltage launcher - realistically they're mostly just used for quickstep and pretty much all default launchers are crap compared to something like Nova.
