### ISSUE TITLE
Musicolet Crashing 

### ISSUE THREAD

**Issue by Tomushiki** [cawilliamson/treble_voltage#17]
Crashing when put to keep playing in background

Got logs
[musicolet log.txt](https://github.com/cawilliamson/treble_voltage/files/14445759/musicolet.log.txt)

It's not too serious so you can attend to it later, but don't forget in the next update

I love the work you're doing here man
Switched from AOSP A14 to Voltage OS dirty Flash and it just updated and is stable asf😁

Thanks for your work man, I appreciate it
Any telegram group link?

**Comment by cawilliamson** [comment]
Hey,

I'm not seeing any app crashes in this logcat.

I play audio in the background frequently and have zero issues with the ROM. I also installed Musicolet and backgrounded it - zero issues with playback - no crashes.

Telegram: https://t.me/ahnetgsi
