### ISSUE TITLE
MicroG release

### ISSUE THREAD

**Issue by fparri** [cawilliamson/treble_voltage#21]
Would it be feasible to create a version of the ROM that includes MicroG alongside the one with Gapps? Installing MicroG on GSI images can be quite challenging, so having a pre-configured image would be immensely helpful 🙏

**Comment by cawilliamson** [comment]
Hmm it's not the worst idea - will look in to it! :+1:

**Comment by cawilliamson** [comment]
I've added a bunch of commits to address this - expect to see microG builds soon! :)

**Comment by fparri** [comment]
Thanks a lot! :))))
