### ISSUE TITLE
Boot problem

### ISSUE THREAD

**Issue by Hiroumuims** [cawilliamson/treble_voltage#22]
My phone got booted in your RoM for 1 hour until now it still booting and my phone gets overheated

**Comment by cawilliamson** [comment]
... so you thought the best thing to do was to post an issue and provide me zero information about your device or how you flashed it? :(

**Comment by Jazkieplayzz000** [comment]
No, what i mean to say is the boot to go through in the splash won't go
through

**Comment by Hiroumuims** [comment]
Its fine
