### ISSUE TITLE
Magisk MicroG install blocked by Gms Compat

### ISSUE THREAD

**Issue by inmaldrerah** [cawilliamson/treble_voltage#27]
I cannot install MicroG correctly with nift4's module on the vanilla version. On install it says that installing vending is blocked to avoid breaking gmscompat, and microG breaks on reboot.

![Screenshot_20240326-094800_KernelSU](https://github.com/cawilliamson/treble_voltage/assets/71413779/054ba42e-b9e4-4b41-9649-9e6ef027ea86)

I know there is a standalone MicroG build. Is this the reason why it is built separately?

**Comment by inmaldrerah** [comment]
Also, there is no microg in the microg build as I mentioned [here](https://github.com/cawilliamson/treble_voltage/issues/24#issuecomment-2019263549).

**Comment by cawilliamson** [comment]
No, this is the module at fault - not the ROM.

I'm afraid there's really nothing I can do to fix this BUT there will be a new build soon with working microG.
