### ISSUE TITLE
VoltageOS 3.2-20240404 release missing

### ISSUE THREAD

**Issue by Alien-Tec** [cawilliamson/treble_voltage#29]
As I can see, your github action was completed successfully, but the files are missing in the release section.

**Comment by erickmufath** [comment]
You mean about the text "Build GSI Passing"? I thought it wasn't a sign of a new release but a sign that there were no errors in the project when it was build, am I wrong?

**Comment by cawilliamson** [comment]
A successful build doesn't mean a successful boot. ;)
