### ISSUE TITLE
face unlock not working

### ISSUE THREAD

**Issue by chetan-go** [cawilliamson/treble_voltage#30]
for me all other things are working except face unlock other than that this gsi is wow i am using redmi 9i and there is even brightness slider bug it does not work properly for me i dont know if it is gsi or device issue

**Comment by erickmufath** [comment]
I have no issue about face unlock and brightness slider, so it's possibly a device issue

**Comment by chetan-go** [comment]
maybe

**Comment by chetan-go** [comment]
what about new ver will we get any update

**Comment by cawilliamson** [comment]
It's 100% a device issue - you should raise a ticket on https://github.com/TrebleDroid/treble_experimentations/issues for your specific device and add as much info about your device as possible.

If your decice is arm32_binder64 though I wouldn't expect this to work.

New update coming as soon as I can build it and get it to boot!
