### ISSUE TITLE
Use this image as a super-image?

### ISSUE THREAD

**Issue by NoelGisler** [cawilliamson/treble_voltage#31]
my Phone (a Unihertz Jelly Star) uses a Super Image instead of a System image. Is there any way to convert this System Image into a super image?

**Comment by cawilliamson** [comment]
Almost ALL devices use a super image.

You have to reboot to fastboot mode (i.e. `adb reboot fastboot`) and then you can fastboot flash system `VoltageOS-blah-blah.img`
