### ISSUE TITLE
Question: how to move to a newer kernel release ?

### ISSUE THREAD

**Issue by D0nnieD4rk0** [cawilliamson/treble_voltage#32]
I haven't been able to find any guides on how to install a newer kernel on a GSI. I've opened this issue to ask for a method you would recommend for installing kernel 4.19 or higher. A link to a guide post is fine

thanks in advance. This project is really great

**Comment by cawilliamson** [comment]
Kernels are nothing to do with GSI - you would need a device specific kernel (likely on XDA Developers or similar) if one exists at all. For a lot of the Chinese phones - there are no kernel sources so you're stuck on the older version until TrebleDroid manage to find a workaround.
