### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by chetan-go** [cawilliamson/treble_voltage#33]
i just wanted a feature request to change status bar and that tray where we find wifi,  torch all that option like to change it to like miui or realme style or atleast change that square to cylinder like how in pixel phone for better reference to which i am reffering i am sending a screen short of that tray
![OIP (2)](https://github.com/cawilliamson/treble_voltage/assets/141745140/6e4c6e69-0a32-4b0a-8c6c-f895430462c7)

**Comment by cawilliamson** [comment]
I don't build the ROM - I just maintain the GSI adaptation of it.

Feature requests of that nature will have to go to the VoltageOS team themselves mate. :)

https://t.me/VoltageOS
