### ISSUE TITLE
Problem with sms and calls

### ISSUE THREAD

**Issue by mohammed-saleh2007** [cawilliamson/treble_voltage#35]
I have  flashed latest version now but this is only gsi have this problem and I hope it was fixed in the new version, I can make calls and send SMS but every time i reboot i can not receive calls or sms until i make one of them to return them works call some one to be able to receive calls

device: Samsung A13 (mtk helio G80) SM-A137f
VoltageOS-microg-arm32_binder64-ab-3.3-20240508-UNOFFICIAL

**Comment by cawilliamson** [comment]
This sounds like a device specific issue but the upcoming build has the latest TD patches so hopefully it will resolve this.

If not - I suggest raising a ticket at: https://github.com/TrebleDroid/treble_experimentations/issues
