### ISSUE TITLE
ab64 [binder] Kernel 4.19.+ wasn't boot

### ISSUE THREAD

**Issue by depersonal** [cawilliamson/treble_voltage#36]
Tested on old devices, 

*VoltageOS 3.4-20240508* splash screen repeat

[ab64 tested]
- Infinix smart 5, hot 10 lite [X657B] not C series
- Based on Android 11 - Kernel 4.19.127
- 64/3, Mediatek(binder)
- Dirty-flash recovery

*VoltageOS 3.2-20240316* booted all fine

[ab64 tested]
- Dirty-flash recovery
- Bluetooth works, GG
- Video sometimes isn't showing

there is the result. any suggest devs? or maybe my kernel have problem or wasn't supported?

how can i compile apps?

Nice roms tho! i love it

**Comment by cawilliamson** [comment]
The upcoming build should contain a patch for this - certain device/kernel combos were broken in the latest build but the upcoming one will have TD fixes for those breakages. :+1:
