### ISSUE TITLE
Microg build still doesn't seem to work

### ISSUE THREAD

**Issue by erickmufath** [cawilliamson/treble_voltage#37]
![Screenshot_20240515-121953](https://github.com/cawilliamson/treble_voltage/assets/90117993/db7145a7-63ea-44aa-953f-24cc0001fd85)
![Screenshot_20240515-123633](https://github.com/cawilliamson/treble_voltage/assets/90117993/4aa33c6a-2018-4621-a0d2-e99b357dca9c)
1. Logically Apps by grapheneos that can help install gapps should be gone because their job has been replaced by MicroG, but it's still there.
2. Because MicroG apps and settings missing or still wasn't working, i tried to install gapps via Apps by grapheneos, but the result is error, i think some of the MicroG configurations that were "running" conflicted with it.

**Comment by Alien-Tec** [comment]
@cawilliamson 
Please, please just get rid of gapps.
There are so many custom roms out there that offer gapps builds only.
Simply stick to vanilla and microG.
That would be awesome.

**Comment by cawilliamson** [comment]
> @cawilliamson Please, please just get rid of gapps. There are so many custom roms out there that offer gapps builds only. Simply stick to vanilla and microG. That would be awesome.

gapps isn't causing the issue - GmsCompat is. I'm working on it and only adding GmsCompat to vanilla builds.

**Comment by erickmufath** [comment]
@cawilliamson
I never install Voltage with Gapps build, but same as MicroG build, if Apps by grapheneos is still there, i think it's not necessary. Also all configuration about that app. Currently used Vanilla build before MicroG works.

**Comment by cawilliamson** [comment]
Fixed in latest release - have fun! :)
