### ISSUE TITLE
Pls, add Lynix patches for lower kernel's 3.14 up

### ISSUE THREAD

**Issue by TheGreatUnknown-One** [cawilliamson/treble_voltage#39]
Hi Chris 👋 nice that you continue to maintain VoltageOS 😁🤗🥳👍

Too bad VoltageOS 3.4EOL and 3.5 don't boot on my device with kernel 4.4.146.
Stuck on OEM logo.

Andy's LOS don't boot
Ponce's AOSP don't boot
LeafOS don't boot
TD don't boot

Only RisingOS 3.2 boots with Lynix patches.https://github.com/ItsLynix/RisingTreble/releases

![Screenshot_20240813-195236_Mercurygram_1](https://github.com/user-attachments/assets/7b3a5a02-4d49-439a-a21b-c57981004960)
Pls, add these patches in you're next built

The last VoltageOS that booted was March 3.2.

I have also tried to patch the kernel, but it does not work.
CONFIG_KALLSYMS_ALL=n

I have to find a solution to recompile the kernel to make it work.

But it's an MTK device, which you know, difficult, no kernel sources 😏

**Comment by cawilliamson** [comment]
Looking into it with you now on Telegram - will close this ticket and keep communicating with you there :D
