### ISSUE TITLE
Little Bug - Digital Wellbeing and parental control! 

### ISSUE THREAD

**Issue by pitekkate** [cawilliamson/treble_voltage#40]
Hallo William,

[ * ] I see little bug,Icon and function Digital Wellbeing and parental control.
![Screenshot_2024-08-10_073642](https://github.com/user-attachments/assets/486620ae-85e8-43ea-af6a-42ff44cf6389)

I'm test on my device 2 day,VoltageOs work OK.

Device: Infinix X690b
Ram.   : 8G
Gsi.      : VoltaveOS-gapps-arm64-ab

[ * ] Tested work with sometimes open browser is crash... (Chrome).
I'm not have log...

Thanks for you

**Comment by cawilliamson** [comment]
There's nothing I can really do to help with this without a log I'm afraid. :(
