### ISSUE TITLE
Voltage OS booting but also not?

### ISSUE THREAD

**Issue by Draygon0** [cawilliamson/treble_voltage#41]
Voltage OS arm32_binder64(gapps) boots on kernel 4.14.199 but quickly reverts back to the Voltage OS booting screen when trying to go through the device setup screen and the cycle repeats itself.

**Comment by cawilliamson** [comment]
Any logcat? Not much I can do without that I'm afraid!

**Comment by Draygon0** [comment]
> Any logcat? Not much I can do without that I'm afraid!

I'm sorry to bother you but I'm not familiar with the process of gathering logs, what exactly should I do?

**Comment by FernFranc** [comment]
Guess I'll close this issue since the behaviour occurs way too fast to even get a logcat.

**Comment by Draygon0** [comment]
Fyi logs cannot be captured since the behaviour occurs way too quickly. Sorry for wasting your time.
