### ISSUE TITLE
Poco m5s Not Sim card detected

### ISSUE THREAD

**Issue by zirangua** [cawilliamson/treble_voltage#42]
>> boot ok >>
>> audio ok >>
>> wifi ok >>

But i do not detect Sim card... 
I tried activate IMS but Install IMS APK is no Supported

**Comment by cawilliamson** [comment]
Could be related to QcRilAm - poke around in that app (may need to launch it from settings) - eSIM management stuff.

If all else fails - try ejecting and reinserting the SIM maybe? But yeah I'd start by playing around with QcRilAm.

**Comment by cawilliamson** [comment]
Going to close this due to lack of activity on it - hopefully you got things working properly! :)
