### ISSUE TITLE
Stuck at boot animation 

### ISSUE THREAD

**Issue by walker425** [cawilliamson/treble_voltage#5]
This last version 3.1 20240121 is stuck at boot animation on my medietake infinix note 11. The other versions were booting but this one isn't.

**Comment by cawilliamson** [comment]
Please try the new build for today: VoltageOS 3.1-20240121-2

Should solve various MTK boot issues.

**Comment by walker425** [comment]
Thanks 👍👍 for this fix, my device successfully booted.

**Comment by walker425** [comment]
Thanks once more for this fix
