### ISSUE TITLE
[question] patches for storage scopes

### ISSUE THREAD

**Issue by LeOS-GSI** [cawilliamson/treble_voltage#6]
Hi, 
have you patches for the storage scopes features. I can't find any for packages/apps/Settings.
or is it hard coded in you packages/apps/Settings repo ?

**Comment by cawilliamson** [comment]
We talked about this on the TrebleDroid telegram channel - to repeat here for anyone else though: I don't know exactly where the patches are applied since this is done by the VoltageOS team themselves. Not me!

Best of luck digging them out though. :)

**Comment by LeOS-GSI** [comment]
I have used a different way. I have build a LeOS-GSI based on your voltage sources 😁. It's in testing phase now. I have removed most default apps, added my LeOS stuff. 
In the moment I'm searching for a way to stop the force encryption. But all other is working find. Nice features, good work 👍
