### ISSUE TITLE
Request for a64 BVN VNDKlite or VNDK GSI

### ISSUE THREAD

**Issue by 4adbfa76** [cawilliamson/treble_voltage#9]
I love your GSI though i can only used LeOS fork of it which is degoogle and i have friends that i help install GSI on their phones but they use devices that is a6a version.

I will love that they use your GSI since it has lots of privacy enhancement.

**Comment by cawilliamson** [comment]
I'll look in to this!

**Comment by 4adbfa76** [comment]
OK. Thanks.

**Comment by cawilliamson** [comment]
I have now added a build for a64 (aka arm32_binder64) here:

https://github.com/cawilliamson/treble_voltage/releases/tag/3.2-20240206

Please open a new ticket if you find any problems. I suspect face unlock MAY not work - not 100% sure.

**Comment by 4adbfa76** [comment]
Thanks for your effort. I have been testing it since yesterday, seems no issues.
No face unlock in security settings to test it but i feel i don't need it.

Thanks again.
